/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;
import entidade.Agendamento;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.List;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Mello_PC
 */
public class Frm_Agendamentos_Retroativos extends javax.swing.JFrame {
DefaultTableModel modelo = new DefaultTableModel();
List<Agendamento> agendamentos = new ArrayList();
Agendamento objAgendamento = new Agendamento();
List<entidade.Servico>servicos = new ArrayList();
private dao.AgendamentoDAO objAgendamentoDAO = new dao.AgendamentoDAO();
Calendar calendar = new GregorianCalendar();
SimpleDateFormat formatadorSql = new SimpleDateFormat("yyyy-MM-dd");
    /**
     * Creates new form Frm_Agendamentos_Retroativos
     */
    public Frm_Agendamentos_Retroativos(List<Agendamento> listaAgendamentos) {
        initComponents();
        agendamentos = listaAgendamentos;
         modelo = (DefaultTableModel)tblresultado.getModel();
         while(modelo.getRowCount()>0){
                        modelo.removeRow(0);
                    }
         agendamentos.stream().forEach((p) -> {
                        modelo.addRow(new Object[] {p.getCodigo(),p.getData(), p.getCliente().getCodigo(), p.getHoraInicial(),p.getHoraFinal(), p.getValorAgendamento()});
                    });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblresultado = new javax.swing.JTable();
        bt_alterar = new javax.swing.JButton();
        bt_modificarStatus = new javax.swing.JButton();
        bt_cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("BeautySystem - Agendamentos Retroativos");

        jLabel1.setText("Agendamentos que se encontram em aberto ");

        tblresultado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo ", "Data", "Cliente", "Hora Inicial", "Hora Final", "Valor Mão de Obra"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblresultado);

        bt_alterar.setText("Alterar");
        bt_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_alterarActionPerformed(evt);
            }
        });

        bt_modificarStatus.setText("Modificar Status");
        bt_modificarStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_modificarStatusActionPerformed(evt);
            }
        });

        bt_cancelar.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bt_alterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_modificarStatus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_cancelar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(187, 187, 187))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_alterar)
                    .addComponent(bt_modificarStatus)
                    .addComponent(bt_cancelar))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void atualizaTabela()
    {
        agendamentos = objAgendamentoDAO.consultarDataRetro(formatadorSql.format(calendar.getTime()));
         modelo = (DefaultTableModel)tblresultado.getModel();
         while(modelo.getRowCount()>0){
                        modelo.removeRow(0);
                    }
         agendamentos.stream().forEach((p) -> {
                        modelo.addRow(new Object[] {p.getCodigo(),p.getData(), p.getCliente().getCodigo(), p.getHoraInicial(),p.getHoraFinal(), p.getValorAgendamento()});
                    });
    }
    private void bt_modificarStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_modificarStatusActionPerformed
     popularAtributos();
        Frm_Modificar_Status f1 = new Frm_Modificar_Status(objAgendamento, Frm_Agendamentos_Retroativos.this,2);
        f1.setVisible(true);
    }//GEN-LAST:event_bt_modificarStatusActionPerformed
 private void popularAtributos()
    {
        int index = tblresultado.getSelectedRow();
        objAgendamento.setCodigo(agendamentos.get(index).getCodigo());
        objAgendamento.setCliente(agendamentos.get(index).getCliente());
        objAgendamento.setData(agendamentos.get(index).getData());
        objAgendamento.setFuncionario(agendamentos.get(index).getFuncionario());
        objAgendamento.setHoraFinal(agendamentos.get(index).getHoraFinal());
        objAgendamento.setHoraInicial(agendamentos.get(index).getHoraInicial());
        objAgendamento.setValorAgendamento(agendamentos.get(index).getValorAgendamento());
        objAgendamento.setObservacao(agendamentos.get(index).getObservacao());
        servicos = agendamentos.get(index).getServicos();
        objAgendamento.setServicos(servicos);
        objAgendamento.setStatus(agendamentos.get(index).getStatus());
    }
    private void bt_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_alterarActionPerformed
     popularAtributos();
     Frm_Realizar_Agendamento f1 = new Frm_Realizar_Agendamento(objAgendamento, 1);
        f1.setVisible(true);
        dispose();
    }//GEN-LAST:event_bt_alterarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Agendamentos_Retroativos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Agendamentos_Retroativos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Agendamentos_Retroativos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Agendamentos_Retroativos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_Agendamentos_Retroativos(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_alterar;
    private javax.swing.JButton bt_cancelar;
    private javax.swing.JButton bt_modificarStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblresultado;
    // End of variables declaration//GEN-END:variables
}
