/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import com.sun.prism.paint.Color;
import entidade.Funcionario;
import entidade.Cliente;
import entidade.Servico;
import entidade.Agendamento;
import java.awt.HeadlessException;
import java.sql.Time;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.List;
import java.util.function.Consumer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mello_PC
 */
public class Frm_Realizar_Agendamento extends javax.swing.JFrame {

  Funcionario objFuncionario = new Funcionario();
  private dao.FuncionarioDAO objFuncionarioDAO = new dao.FuncionarioDAO();
  Cliente objCliente = new Cliente();
  private dao.ClienteDAO objClienteDAO = new dao.ClienteDAO();
  Agendamento objAgendamento = new Agendamento();
  Servico objServico = new Servico();
  private dao.ServicoDAO objServicoDAO = new dao.ServicoDAO();
  private List <entidade.Servico> servicos = new ArrayList();
  private DefaultTableModel modelo = new DefaultTableModel();
  private List<Agendamento> agendamentos = new ArrayList();
  Date data = new Date();
  Date dataHoraIni = new Date();
  Date dataHoraFin = new Date();
  Date date = new Date();
  Date date2 = new Date();
  int op;
  SimpleDateFormat formatador = new SimpleDateFormat("dd/MM/yyyy");
  Calendar calendar = new GregorianCalendar();
  private dao.AgendamentoDAO objAgendamentoDAO = new dao.AgendamentoDAO();
    public Frm_Realizar_Agendamento(Agendamento objAgendamentoPesq, int op) {
        initComponents();
        setLocationRelativeTo(null);
        formatador.setLenient(false);
        this.op = op;
        if (op==1)
            {
            tb_codigoAgendamento.setText(String.valueOf(objAgendamentoPesq.getCodigo()));
            tb_clienteAgendamento.setText(String.valueOf(objAgendamentoPesq.getCliente().getCodigo()));
            lb_clienteAgendamento.setText(objAgendamentoPesq.getCliente().getNome());
            tb_funcAgendamento.setText(String.valueOf(objAgendamentoPesq.getFuncionario().getCodigo()));
            lb_descFuncionario.setText(objAgendamentoPesq.getFuncionario().getNome());
            data = objAgendamentoPesq.getData();
            tb_dataAgendamento.setText(formatador.format(data));
            tb_horaInicialAgendamento.setText(objAgendamentoPesq.getHoraInicial());
            tb_horaFinalAgendamento.setText(objAgendamentoPesq.getHoraFinal());
             objAgendamento.setValorAgendamento(objAgendamentoPesq.getValorAgendamento());
            lb_valorParcialAgendamento.setText(String.valueOf(objAgendamento.getValorAgendamento()));
            servicos = objAgendamentoPesq.getServicos();
            objAgendamento.setServicos(servicos);
            if(servicos.size()>0)
             {
             modelo = (DefaultTableModel)tblServicos.getModel();
                    while(modelo.getRowCount()>0){
                        modelo.removeRow(0);
         }
                    servicos.stream().forEach((p) -> {
                       modelo.addRow(new Object[]{p.getCodigo(), p.getDescricao(),p.getQuantidade(), p.getValorMaoDeObra() });
                    });
            }
           
            }
        else 
        {
            tb_codigoAgendamento.setText(Integer.toString(objAgendamentoDAO.retornaCodigo()));
            JTab.setEnabledAt( 1, false );
            objAgendamento.setValorAgendamento(0.00);
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JTab = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        tb_clienteAgendamento = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        bt_pesquisaFuncAgendamento = new javax.swing.JButton();
        lb_valorParcialAgendamento = new javax.swing.JLabel();
        bt_pesquisarClienteAgendamento = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        tb_codigoAgendamento = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        tb_funcAgendamento = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tb_horaFinalAgendamento = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblServicos = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        bt_removerServico = new javax.swing.JButton();
        lb_descFuncionario = new javax.swing.JLabel();
        lb_clienteAgendamento = new javax.swing.JLabel();
        tb_dataAgendamento = new javax.swing.JFormattedTextField();
        tb_horaInicialAgendamento = new javax.swing.JFormattedTextField();
        lb_consultaDisponibilidade = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        tb_codigoServico = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tb_quantidadeServico = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tb_valorServico = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        lb_descServico = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("BeautySystem - Ralizar Agendamento");

        tb_clienteAgendamento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tb_clienteAgendamentoFocusLost(evt);
            }
        });

        jLabel6.setText("Valor Parcial do Agendamento (Mão de Obra):");

        bt_pesquisaFuncAgendamento.setText("Pesquisar...");
        bt_pesquisaFuncAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_pesquisaFuncAgendamentoActionPerformed(evt);
            }
        });

        bt_pesquisarClienteAgendamento.setText("Pesquisar...");
        bt_pesquisarClienteAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_pesquisarClienteAgendamentoActionPerformed(evt);
            }
        });

        jButton2.setText("Inserir Serviço");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton5.setText("Verificar Agenda no Dia");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton3.setText("Finalizar Agendamento");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Cancelar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel7.setText("Código:");

        tb_codigoAgendamento.setEditable(false);

        jLabel1.setText("Funcionário:");

        jLabel2.setText("Data:");

        jLabel3.setText("Hora Inicial:");

        jLabel4.setText("Hora Final:");

        jButton1.setText("Verificar Disponibilidade de Funcionário");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tb_funcAgendamento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tb_funcAgendamentoFocusLost(evt);
            }
        });

        jLabel5.setText("Lista de Serviços");

        try {
            tb_horaFinalAgendamento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tb_horaFinalAgendamento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tb_horaFinalAgendamentoFocusLost(evt);
            }
        });

        tblServicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Serviço", "Quantidade", "Valor Mão de Obra"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblServicos);

        jLabel8.setText("Cliente:");

        bt_removerServico.setText("Remover Serviço");
        bt_removerServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_removerServicoActionPerformed(evt);
            }
        });

        try {
            tb_dataAgendamento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tb_dataAgendamento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tb_dataAgendamentoFocusLost(evt);
            }
        });

        try {
            tb_horaInicialAgendamento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tb_horaInicialAgendamento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tb_horaInicialAgendamentoFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(lb_valorParcialAgendamento)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tb_funcAgendamento, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_pesquisaFuncAgendamento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_descFuncionario)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tb_codigoAgendamento, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(tb_clienteAgendamento, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bt_pesquisarClienteAgendamento)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lb_clienteAgendamento))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tb_horaInicialAgendamento, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tb_dataAgendamento, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton5))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jButton2)
                                    .addGap(18, 18, 18)
                                    .addComponent(bt_removerServico)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButton3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton4))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tb_horaFinalAgendamento, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lb_consultaDisponibilidade)))
                        .addGap(0, 13, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tb_codigoAgendamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tb_clienteAgendamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(bt_pesquisarClienteAgendamento)
                    .addComponent(lb_clienteAgendamento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tb_funcAgendamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addComponent(bt_pesquisaFuncAgendamento))
                    .addComponent(lb_descFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jButton5)
                    .addComponent(tb_dataAgendamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tb_horaInicialAgendamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tb_horaFinalAgendamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(lb_consultaDisponibilidade))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(lb_valorParcialAgendamento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(bt_removerServico)
                    .addComponent(jButton4))
                .addGap(15, 15, 15))
        );

        JTab.addTab("Agendamento", jPanel1);

        jLabel9.setText("Código:");

        tb_codigoServico.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tb_codigoServicoFocusLost(evt);
            }
        });

        jLabel10.setText(" Quantidade:");

        jLabel11.setText("Valor Mão de Obra:");

        jButton6.setText("Inserir");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Cancelar");

        jButton8.setText("Pesquisar...");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tb_codigoServico, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_descServico))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tb_quantidadeServico, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tb_valorServico, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7)))
                .addContainerGap(338, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tb_codigoServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8)
                    .addComponent(lb_descServico))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tb_quantidadeServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tb_valorServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton7))
                .addContainerGap(233, Short.MAX_VALUE))
        );

        JTab.addTab("Itens", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JTab, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JTab)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
     private void cancelar()
    {
        if(javax.swing.JOptionPane.showConfirmDialog(null,"Deseja Cancelar a Operacao?","ATENÇÂO ",javax.swing.JOptionPane.YES_NO_OPTION)==0)
        {
            dispose();
        }
    }
    private boolean validarCampos()
    {
        return(!tb_codigoAgendamento.getText().equals(""))&&(
                !tb_clienteAgendamento.getText().equals(""))&&
                !tb_dataAgendamento.getText().equals("")&&(
                !tb_funcAgendamento.getText().equals(""))&&(
                !tb_horaInicialAgendamento.getText().equals(""))&&(
                !tb_horaFinalAgendamento.getText().equals(""));
                
    }
    private boolean consultarDisponibilidade() throws ParseException
    {
        objAgendamento.setCodigo(Integer.valueOf(tb_codigoAgendamento.getText()));
        SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy"); 
        java.sql.Date data1 = new java.sql.Date(format.parse(tb_dataAgendamento.getText()).getTime());
        objAgendamento.setData(data1);
        agendamentos =objAgendamentoDAO.consultarDisponibiblidade(tb_horaInicialAgendamento.getText(), tb_horaFinalAgendamento.getText(),Integer.valueOf(tb_funcAgendamento.getText()),objAgendamento);
        if(agendamentos.size()>0){
         lb_consultaDisponibilidade.setForeground(java.awt.Color.RED);
         lb_consultaDisponibilidade.setText("Horário Indisponível");
            tb_funcAgendamento.requestFocus();
            return false;
        }
        else
            lb_consultaDisponibilidade.setForeground(java.awt.Color.GREEN);
         lb_consultaDisponibilidade.setText("Horário Disponível");  
            return true;
    }
    private boolean validarCamposItem()
    {
        return (!tb_codigoServico.getText().equals(""))&&
                (Integer.parseInt(tb_quantidadeServico.getText())>0)&&
                (Double.parseDouble(tb_valorServico.getText())>0);
    }
    private void popularAtributos() throws ParseException
    {
        objAgendamento.setCodigo(Integer.parseInt(tb_codigoAgendamento.getText()));
        objAgendamento.setCliente(objClienteDAO.consultar(Long.parseLong(tb_clienteAgendamento.getText())));
        objAgendamento.setFuncionario(objFuncionarioDAO.consultar(Long.parseLong(tb_funcAgendamento.getText())));
        objAgendamento.setHoraInicial(tb_horaInicialAgendamento.getText());
        objAgendamento.setHoraFinal(tb_horaFinalAgendamento.getText());
        SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy"); 
        java.sql.Date data = new java.sql.Date(format.parse(tb_dataAgendamento.getText()).getTime());
        objAgendamento.setData(data);
        objAgendamento.setStatus("Agendado");
    }
    public void setTb_Cliente(String conteudo)
    {
        tb_clienteAgendamento.setText(conteudo);
        tb_clienteAgendamento.requestFocus();
    }
    
    public void setTb_Funcionario(String conteudo)
    {
        tb_funcAgendamento.setText(conteudo);
        tb_funcAgendamento.requestFocus();
    }
    public void setTb_Servico(String Conteudo)
    {
        tb_codigoServico.setText(Conteudo);
        tb_codigoServico.requestFocus();
    }
    private void tb_clienteAgendamentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tb_clienteAgendamentoFocusLost
     lb_clienteAgendamento.setText(objClienteDAO.consultar(Long.parseLong(tb_clienteAgendamento.getText())).getNome());
     objCliente = objClienteDAO.consultar(Long.parseLong(tb_clienteAgendamento.getText()));
     if(objCliente.getNome()== null)
        {
            JOptionPane.showMessageDialog(this, "Nenhum registro encontrado!", "Informação", JOptionPane.INFORMATION_MESSAGE);
            tb_clienteAgendamento.requestFocus();
            tb_clienteAgendamento.setText("");
            lb_clienteAgendamento.setText("");
        }
     else if(objCliente.getSituacao().equals("Bloqueado"))
        {
            JOptionPane.showMessageDialog(this, "Cliente "+objCliente.getNome()+" Bloqueado!", "Informação", JOptionPane.INFORMATION_MESSAGE);
            tb_clienteAgendamento.requestFocus();
            tb_clienteAgendamento.setText("");
            lb_clienteAgendamento.setText("");
            JTab.setSelectedIndex(0);
        }
     else
     tb_funcAgendamento.requestFocus();
    }//GEN-LAST:event_tb_clienteAgendamentoFocusLost

    private void bt_pesquisarClienteAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_pesquisarClienteAgendamentoActionPerformed
    Frm_Cons_Cliente2 f1 = new Frm_Cons_Cliente2(Frm_Realizar_Agendamento.this,2);
    f1.setVisible(true);
    }//GEN-LAST:event_bt_pesquisarClienteAgendamentoActionPerformed

    private void tb_funcAgendamentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tb_funcAgendamentoFocusLost
     lb_descFuncionario.setText(objFuncionarioDAO.consultar(Long.parseLong(tb_funcAgendamento.getText())).getNome());
     tb_dataAgendamento.requestFocus();
    }//GEN-LAST:event_tb_funcAgendamentoFocusLost

    private void bt_pesquisaFuncAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_pesquisaFuncAgendamentoActionPerformed
   Frm_Cons_Func_Venda f1 = new Frm_Cons_Func_Venda(Frm_Realizar_Agendamento.this,2);
    f1.setVisible(true);
    }//GEN-LAST:event_bt_pesquisaFuncAgendamentoActionPerformed
                                              
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      try {
          if(consultarDisponibilidade())
          {
              if(validarCampos()&&!tb_dataAgendamento.getText().equals("  /  /    "))
              {
                  JTab.setSelectedIndex(1);}
              else
              {
                  JOptionPane.showMessageDialog(this, "Preencha todos os campos do agendamento!", "Informação", JOptionPane.INFORMATION_MESSAGE);
                
    }//GEN-LAST:event_jButton2ActionPerformed
    }
    else
    consultarDisponibilidade();
    } catch (ParseException ex) {
          Logger.getLogger(Frm_Realizar_Agendamento.class.getName()).log(Level.SEVERE, null, ex);
      }
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       if(op==1)
       {
           try{
            popularAtributos();
            objAgendamentoDAO.editar(objAgendamento);
            JOptionPane.showMessageDialog(this, "Registro inserido com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            dispose();
        } catch (NumberFormatException | HeadlessException e){
            JOptionPane.showMessageDialog(this, "Erro"+e);
        } catch (ParseException ex) { 
          Logger.getLogger(Frm_Realizar_Agendamento.class.getName()).log(Level.SEVERE, null, ex);
      }
       }
       else{
        try{
            popularAtributos();
            objAgendamentoDAO.gravar(objAgendamento);
            JOptionPane.showMessageDialog(this, "Registro inserido com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            dispose();
        } catch (NumberFormatException | HeadlessException e){
            JOptionPane.showMessageDialog(this, "Erro"+e);
        } catch (ParseException ex) { 
          Logger.getLogger(Frm_Realizar_Agendamento.class.getName()).log(Level.SEVERE, null, ex);
      } 
    }//GEN-LAST:event_jButton3ActionPerformed
    }
    private void tb_codigoServicoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tb_codigoServicoFocusLost
        objServico = objServicoDAO.consultar(Long.parseLong(tb_codigoServico.getText()));
        if(objServico.getDescricao()!=null)
        {
           lb_descServico.setText(objServico.getDescricao());
        tb_quantidadeServico.setText("1");
        tb_valorServico.setText(Double.toString(objServico.getValorMaoDeObra())); 
        }
        else 
        {
            JOptionPane.showMessageDialog(this, "Nenhum registro encontrado!", "Informação", JOptionPane.INFORMATION_MESSAGE);
        tb_codigoServico.requestFocus();
        tb_codigoServico.setText("");
        }
    }//GEN-LAST:event_tb_codigoServicoFocusLost

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if(validarCamposItem())
        {
            objServico.setQuantidade(Integer.parseInt(tb_quantidadeServico.getText()));
            objServico.setValorMaoDeObra(Double.parseDouble(tb_valorServico.getText()));
            objAgendamento.getServicos().add(objServico);
            modelo = (DefaultTableModel)tblServicos.getModel();
            modelo.addRow(new Object[]{objServico.getCodigo(), objServico.getDescricao(),objServico.getQuantidade(), objServico.getValorMaoDeObra() });
            objAgendamento.setValorAgendamento(objAgendamento.getValorAgendamento()+(objServico.getQuantidade()*objServico.getValorMaoDeObra()));
            lb_valorParcialAgendamento.setText(Double.toString(objAgendamento.getValorAgendamento()));
            JTab.setSelectedIndex(0);
            tb_codigoServico.setText("");
            tb_quantidadeServico.setText("");
            tb_valorServico.setText("");
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
    Frm_Cons_Ser2 f1 = new Frm_Cons_Ser2(Frm_Realizar_Agendamento.this);
    f1.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void tb_horaInicialAgendamentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tb_horaInicialAgendamentoFocusLost
   SimpleDateFormat sdf  = new SimpleDateFormat( "HH:mm" );  
  
    // com set lenient a data não se adapta a numeros  
    // muito grandes. Se não setado, por exemplo ao  
    // inserir 25h a data ficaria como 1h da manhã  
    // do dia seguinte.  
    sdf.setLenient( false );  
    try  
    {  
        dataHoraIni = sdf.parse( tb_horaInicialAgendamento.getText() );  
    }  
    catch( ParseException e )  
    {  
       JOptionPane.showMessageDialog(null, "Horario Inválido: "+e);
       JTab.setSelectedIndex(0);
       tb_horaInicialAgendamento.requestFocus();
    }  
    }//GEN-LAST:event_tb_horaInicialAgendamentoFocusLost

    private void tb_horaFinalAgendamentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tb_horaFinalAgendamentoFocusLost
    SimpleDateFormat sdf  = new SimpleDateFormat( "HH:mm" );   
    sdf.setLenient( false );  
    try  
    {  
        dataHoraFin = sdf.parse( tb_horaFinalAgendamento.getText() );
        if(dataHoraFin.getTime()<=dataHoraIni.getTime())
        {
            JOptionPane.showMessageDialog(null, "Erro: Horario Final Menor ou igual ao inicial");
            tb_horaFinalAgendamento.setText("");
            tb_horaInicialAgendamento.requestFocus();
        }
    }  
    catch( ParseException e )  
    {  
       JOptionPane.showMessageDialog(null, "Horario Inválido: "+e);  
       JTab.setSelectedIndex(0);
       tb_horaFinalAgendamento.requestFocus();
    }  
    }//GEN-LAST:event_tb_horaFinalAgendamentoFocusLost

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
     SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
     java.sql.Date date = null;
      try {
          date = new java.sql.Date(format.parse(tb_dataAgendamento.getText()).getTime());
      } catch (ParseException ex) {
          Logger.getLogger(Frm_Realizar_Agendamento.class.getName()).log(Level.SEVERE, null, ex);
      }
      data = date;
     Frm_Agenda_Funcionario f1 = null;
      try {
          f1 = new Frm_Agenda_Funcionario(objFuncionarioDAO.consultar(Long.parseLong(tb_funcAgendamento.getText())), data);
      } catch (ParseException ex) {
          Logger.getLogger(Frm_Realizar_Agendamento.class.getName()).log(Level.SEVERE, null, ex);
      }
     f1.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void tb_dataAgendamentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tb_dataAgendamentoFocusLost
     try
    {
        date = formatador.parse(tb_dataAgendamento.getText());
        date2 = formatador.parse(formatador.format(calendar.getTime()));
        if(date.getTime()<date2.getTime())
            {
                JOptionPane.showMessageDialog(this, "Data não pode ser menor doque data atual", "Informação", JOptionPane.INFORMATION_MESSAGE);
                tb_dataAgendamento.setText("");
                tb_dataAgendamento.requestFocus();
            }
    }
    catch(ParseException e)
    {
        JOptionPane.showMessageDialog(this, "Data Invalida", "Informação", JOptionPane.INFORMATION_MESSAGE);
        tb_dataAgendamento.setText("");
        tb_dataAgendamento.requestFocus();
    }
    }//GEN-LAST:event_tb_dataAgendamentoFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      try {
          consultarDisponibilidade();
      } catch (ParseException ex) {
          Logger.getLogger(Frm_Realizar_Agendamento.class.getName()).log(Level.SEVERE, null, ex);
      }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bt_removerServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_removerServicoActionPerformed
    int index = tblServicos.getSelectedRow();
    modelo = (DefaultTableModel)tblServicos.getModel();
    double valorServico = objAgendamento.getServicos().get(index).getValorMaoDeObra();
    int quantServico = objAgendamento.getServicos().get(index).getQuantidade();
    objAgendamento.setValorAgendamento(objAgendamento.getValorAgendamento() - (quantServico * valorServico));
    lb_valorParcialAgendamento.setText(String.valueOf(objAgendamento.getValorAgendamento()));
    modelo.removeRow(index);
    objAgendamento.getServicos().remove(index);
    }//GEN-LAST:event_bt_removerServicoActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        cancelar();
    }//GEN-LAST:event_jButton4ActionPerformed

  
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Realizar_Agendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Realizar_Agendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Realizar_Agendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Realizar_Agendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_Realizar_Agendamento(null,0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane JTab;
    private javax.swing.JButton bt_pesquisaFuncAgendamento;
    private javax.swing.JButton bt_pesquisarClienteAgendamento;
    private javax.swing.JButton bt_removerServico;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_clienteAgendamento;
    private javax.swing.JLabel lb_consultaDisponibilidade;
    private javax.swing.JLabel lb_descFuncionario;
    private javax.swing.JLabel lb_descServico;
    private javax.swing.JLabel lb_valorParcialAgendamento;
    private javax.swing.JTextField tb_clienteAgendamento;
    private javax.swing.JTextField tb_codigoAgendamento;
    private javax.swing.JTextField tb_codigoServico;
    private javax.swing.JFormattedTextField tb_dataAgendamento;
    private javax.swing.JTextField tb_funcAgendamento;
    private javax.swing.JFormattedTextField tb_horaFinalAgendamento;
    private javax.swing.JFormattedTextField tb_horaInicialAgendamento;
    private javax.swing.JTextField tb_quantidadeServico;
    private javax.swing.JTextField tb_valorServico;
    private javax.swing.JTable tblServicos;
    // End of variables declaration//GEN-END:variables
}
