/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import java.awt.HeadlessException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Calendar;
import java.text.ParseException;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.Date;

public class Frm_Cad_Pro extends javax.swing.JFrame {

    private entidade.Produto objProduto;
    private dao.ProdutoDAO objProdutoDAO = new dao.ProdutoDAO();
    private entidade.GrupoProdutos objGrupoProdutos = new entidade.GrupoProdutos();
    private dao.GrupoProdutosDAO objGrupoProdutosDAO= new dao.GrupoProdutosDAO();
    private List<entidade.Produto> produtos = new ArrayList();
    Calendar ca = new GregorianCalendar();  
    Date data = new Date(); 
    SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
    String stringData;
    public Frm_Cad_Pro() {
        initComponents();
        this.objProduto = new entidade.Produto();
        objGrupoProdutos = null;
        ca.setTime(data);
        stringData = formato.format(ca.getTime());
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bt_pesquisarGrupo = new javax.swing.JButton();
        tb_descricaoPro = new javax.swing.JTextField();
        tb_valorCompraPro = new javax.swing.JTextField();
        tb_valorVendaPro = new javax.swing.JTextField();
        tb_grupoPro = new javax.swing.JTextField();
        bt_limpar = new javax.swing.JButton();
        bt_Inserir = new javax.swing.JButton();
        bt_cancelar = new javax.swing.JButton();
        lb_descricaoGrupo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("BeautySystem - Cadastro de Produtos");

        jLabel1.setText("Descrição:");

        jLabel2.setText("Valor de Compra:");

        jLabel3.setText("Valor de Venda:");

        jLabel4.setText("Grupo do Produto:");

        bt_pesquisarGrupo.setText("Pesquisar...");
        bt_pesquisarGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_pesquisarGrupoActionPerformed(evt);
            }
        });

        tb_grupoPro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tb_grupoProFocusLost(evt);
            }
        });

        bt_limpar.setText("Limpar");
        bt_limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_limparActionPerformed(evt);
            }
        });

        bt_Inserir.setText("Inserir");
        bt_Inserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_InserirActionPerformed(evt);
            }
        });

        bt_cancelar.setText("Cancelar");
        bt_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tb_descricaoPro, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tb_valorVendaPro, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tb_valorCompraPro, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tb_grupoPro, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bt_pesquisarGrupo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lb_descricaoGrupo))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(bt_limpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_Inserir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_cancelar)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tb_descricaoPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tb_valorCompraPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tb_valorVendaPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(bt_pesquisarGrupo)
                    .addComponent(tb_grupoPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_descricaoGrupo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_limpar)
                    .addComponent(bt_Inserir)
                    .addComponent(bt_cancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
     private void limparCampos()
     {
         tb_descricaoPro.setText("");
         tb_grupoPro.setText("");
         tb_valorVendaPro.setText("");
         tb_valorCompraPro.setText("");
     }
     
     private void cancelar(){  
        if(javax.swing.JOptionPane.showConfirmDialog(null,"Deseja Cancelar a Operacao?","ATENÇÂO ",javax.swing.JOptionPane.YES_NO_OPTION )==0){  
            this.dispose();  
        }
    }  
     
      private boolean validarCampos(){
        return (!tb_descricaoPro.getText().equals("")) &&
                (!tb_grupoPro.getText().equals("")) &&
                (!tb_valorCompraPro.getText().equals("")) &&
                (!tb_valorVendaPro.getText().equals(""));
                }
     
      private void popularAtributos() throws ParseException{
      SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
        objProduto.setDescricao(tb_descricaoPro.getText());
        objProduto.setGrupoProdutos(Integer.valueOf(tb_grupoPro.getText()));
        objProduto.setValorCompra(Double.valueOf(tb_valorCompraPro.getText().replaceAll(",", ".")));
        objProduto.setValorVenda(Double.valueOf(tb_valorVendaPro.getText().replaceAll(",", ".")));
            java.sql.Date data1 = new java.sql.Date(formato.parse(stringData).getTime());  
        objProduto.setDataCadastro(data1);
      }
    private void bt_InserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_InserirActionPerformed
    if(validarCampos()){
            try{
                popularAtributos();
                objProdutoDAO.gravar(objProduto);
                JOptionPane.showMessageDialog(this, "Registro inserido com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                dispose();
            } catch (NumberFormatException | HeadlessException e){
                JOptionPane.showMessageDialog(this, "Erro"+e);
            } catch (ParseException ex) {
            Logger.getLogger(Frm_Cad_Pro.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
        }
    }//GEN-LAST:event_bt_InserirActionPerformed

    private void bt_limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_limparActionPerformed
     limparCampos();
    }//GEN-LAST:event_bt_limparActionPerformed

    private void bt_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cancelarActionPerformed
    cancelar();
    }//GEN-LAST:event_bt_cancelarActionPerformed
    
    private void bt_pesquisarGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_pesquisarGrupoActionPerformed
     Frm_Cons_GrupoPro2 f1 = new Frm_Cons_GrupoPro2(Frm_Cad_Pro.this);
             f1.setVisible(true);
    }//GEN-LAST:event_bt_pesquisarGrupoActionPerformed

    private void tb_grupoProFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tb_grupoProFocusLost
     objGrupoProdutos = objGrupoProdutosDAO.consultar(Long.parseLong(tb_grupoPro.getText()));
     if(objGrupoProdutos.getDescricao() == null)
     {
         JOptionPane.showMessageDialog(this, "Nenhum registro encontrado!", "Informação", JOptionPane.INFORMATION_MESSAGE);
     }
     else{
     lb_descricaoGrupo.setText(objGrupoProdutos.getDescricao());
     bt_Inserir.requestFocus();
     }
    }//GEN-LAST:event_tb_grupoProFocusLost
    
    public void setTb_grupoPro(String conteudo) {
         tb_grupoPro.setText(conteudo);
         tb_grupoPro.requestFocus();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Cad_Pro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Cad_Pro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Cad_Pro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Cad_Pro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_Cad_Pro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_Inserir;
    private javax.swing.JButton bt_cancelar;
    private javax.swing.JButton bt_limpar;
    private javax.swing.JButton bt_pesquisarGrupo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lb_descricaoGrupo;
    private javax.swing.JTextField tb_descricaoPro;
    private javax.swing.JTextField tb_grupoPro;
    private javax.swing.JTextField tb_valorCompraPro;
    private javax.swing.JTextField tb_valorVendaPro;
    // End of variables declaration//GEN-END:variables
}
