/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import entidade.Agendamento;
import entidade.Funcionario;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mello_PC
 */
public class Frm_Agenda_Funcionario extends javax.swing.JFrame {
    
    /**
     * Creates new form Frm_Agenda_Funcionario
     */
    SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
    DefaultTableModel modelo = new DefaultTableModel();
    Funcionario objFuncionario = new Funcionario();
    Date date = new Date();
    private dao.FuncionarioDAO objFuncionarioDAO = new dao.FuncionarioDAO();
    private dao.AgendamentoDAO objAgendamentoDAO = new dao.AgendamentoDAO();
    List<Agendamento> agendamentos = new ArrayList();
    public Frm_Agenda_Funcionario( Funcionario funcionario, Date data) throws ParseException {
        initComponents();
        setLocationRelativeTo(null);
        format.setLenient(false);
        tb_dataAgendamento.setText(format.format(data));
        lb_descFuncionario.setText(funcionario.getNome());
        tb_codigoFuncionario.setText(String.valueOf(funcionario.getCodigo()));
        modelo = (DefaultTableModel)tblagendamento.getModel();
        objFuncionario = funcionario;
        preencherTabela();   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tb_dataAgendamento = new javax.swing.JFormattedTextField();
        tb_codigoFuncionario = new javax.swing.JTextField();
        lb_descFuncionario = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblagendamento = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("BeautySystem - Agenda de Funcionario");

        jLabel1.setText("Data:");

        jLabel2.setText("Funcionario:");

        try {
            tb_dataAgendamento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tb_dataAgendamento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tb_dataAgendamentoFocusLost(evt);
            }
        });

        tb_codigoFuncionario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tb_codigoFuncionarioFocusLost(evt);
            }
        });

        jButton1.setText("Pesquisar Funcionario");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tblagendamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cliente", "Hora Inicial", "Hora Final"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblagendamento);

        jButton2.setText("Verificar Agenda");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tb_dataAgendamento, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tb_codigoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_descFuncionario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(tb_dataAgendamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tb_codigoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_descFuncionario)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void limparTabela()
    {
        while(modelo.getRowCount()>0){
                        modelo.removeRow(0);
         }
    }
    private void preencherTabela() throws ParseException
    {
        if(!tb_codigoFuncionario.getText().equals("")||!tb_dataAgendamento.getText().equals("")){
                java.sql.Date data1 = new java.sql.Date(format.parse(tb_dataAgendamento.getText()).getTime());
         agendamentos = objAgendamentoDAO.verificarAgenda("DataAgendamento", data1.toString(),objFuncionario.getCodigo(),0);
         if( agendamentos.size()>0)
         {
             modelo = (DefaultTableModel)tblagendamento.getModel();
                    while(modelo.getRowCount()>0){
                        modelo.removeRow(0);
         }
                     agendamentos.stream().forEach((p) -> {
                        modelo.addRow(new Object[] {p.getCliente().getNome(),p.getHoraInicial(),p.getHoraFinal()});
                    });
    }                                            
 else
         {
             JOptionPane.showMessageDialog(this, "Nenhum registro encontrado!", "Informação", JOptionPane.INFORMATION_MESSAGE);
             limparTabela();
         }
     }
     else
     {
         JOptionPane.showMessageDialog(this, "Preencha o Campo", "Aviso", JOptionPane.INFORMATION_MESSAGE);
     }
    }
    public void setTb_CodigoFunc(String conteudo)
    {
        tb_codigoFuncionario.setText(conteudo);
        objFuncionario = objFuncionarioDAO.consultar(Long.parseLong(conteudo));
        lb_descFuncionario.setText(objFuncionario.getNome());
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    Frm_Cons_Func_Venda f1 = new Frm_Cons_Func_Venda(Frm_Agenda_Funcionario.this,3);
    f1.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tb_codigoFuncionarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tb_codigoFuncionarioFocusLost
     //objFuncionario = objFuncionarioDAO.consultar(Long.parseLong(tb_codigoFuncionario.getText()));
        objFuncionario = objFuncionarioDAO.consultar(Long.parseLong(tb_codigoFuncionario.getText()));
        if(objFuncionario.getNome()!=null)
        lb_descFuncionario.setText(objFuncionario.getNome());
        else
        {
            JOptionPane.showMessageDialog(this, "Funcionario não Encontrado", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            tb_codigoFuncionario.setText("");
            tb_codigoFuncionario.requestFocus();
        }
    }//GEN-LAST:event_tb_codigoFuncionarioFocusLost

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            preencherTabela();
        } catch (ParseException ex) {
            Logger.getLogger(Frm_Agenda_Funcionario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tb_dataAgendamentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tb_dataAgendamentoFocusLost
     try
    {
        date = format.parse(tb_dataAgendamento.getText());
    }
    catch(ParseException e)
    {
        JOptionPane.showMessageDialog(this, "Data Invalida", "Informação", JOptionPane.INFORMATION_MESSAGE);
        tb_dataAgendamento.setText("");
        tb_dataAgendamento.requestFocus();
    }
    }//GEN-LAST:event_tb_dataAgendamentoFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Agenda_Funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Agenda_Funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Agenda_Funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Agenda_Funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Frm_Agenda_Funcionario(null,null).setVisible(true);
                } catch (ParseException ex) {
                    Logger.getLogger(Frm_Agenda_Funcionario.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_descFuncionario;
    private javax.swing.JTextField tb_codigoFuncionario;
    private javax.swing.JFormattedTextField tb_dataAgendamento;
    private javax.swing.JTable tblagendamento;
    // End of variables declaration//GEN-END:variables
}
