/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import entidade.Funcionario;
import entidade.Produto;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import java.util.GregorianCalendar;
import java.util.Calendar;
import javax.swing.JFrame;

/**
 *
 * @author Mello_PC
 */
public class Frm_Rel_Sugestao_Compras extends javax.swing.JFrame {

    List<Produto> produtos = new ArrayList();
    private dao.ProdutoDAO objProdutoDAO= new dao.ProdutoDAO();
    Calendar calendar = new GregorianCalendar();
    SimpleDateFormat formatador = new SimpleDateFormat("dd/MM/yyyy");
    public Frm_Rel_Sugestao_Compras(Funcionario Principal) {
        if(Principal.getNivelAcesso().equals("Gerente"))
        {
            initComponents();
        setLocationRelativeTo(null);
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Nivel de Acesso não permute acessar esta função!", "Informação", JOptionPane.INFORMATION_MESSAGE);
            dispose();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tb_diasEstoque = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tb_margemSeguranca = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("BeautySystem - Relatório de Sugestão de Compras");

        jLabel1.setText("Estoque para");

        jLabel2.setText("dias");

        jLabel3.setText("Margem de Segurança (%):");

        jButton1.setText("Gerar Relatório de Sugestão de Compras");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Sair");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tb_diasEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel3)
                        .addGap(10, 10, 10)
                        .addComponent(tb_margemSeguranca, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tb_diasEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(tb_margemSeguranca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
gerarRelatorioSugestaoCompras();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    dispose();
    }//GEN-LAST:event_jButton2ActionPerformed
private void criaDiretorio(String novoDiretorio){  
    String nomeDiretorio = null;   
    String separador = java.io.File.separator;   
    try {       
         nomeDiretorio = "C:" + separador + novoDiretorio;   
         if (!new File(nomeDiretorio).exists()) { // Verifica se o diretório existe.   
             (new File(nomeDiretorio)).mkdir();   // Cria o diretório   
         }   
    } catch (Exception ex) {   
         JOptionPane.showMessageDialog(null,"Err","Erro ao criar o diretório" + ex.toString(),JOptionPane.ERROR_MESSAGE);   
    }  
}
private void gerarRelatorioSugestaoCompras()
{
    criaDiretorio("relatoriosBeautySystem");
        Document relatorioSugestao = new Document(PageSize.A4);
            try{
            PdfWriter.getInstance(relatorioSugestao , new FileOutputStream("C:\\relatoriosBeautySystem\\relatorioSugestao.pdf"));
            relatorioSugestao.open();
            Paragraph paragrafo = new Paragraph("Relatorio de Sugestao de Compra");    
             paragrafo.setAlignment(Element.ALIGN_CENTER);
            relatorioSugestao.add(new Paragraph(paragrafo));
            Paragraph paragrafoNomeCli = new Paragraph("Relatório de Sugestão de Compras no dia: "+formatador.format(calendar.getTime()));    
             paragrafoNomeCli.setAlignment(Element.ALIGN_CENTER);
              relatorioSugestao.add(new Paragraph(paragrafoNomeCli));
             Paragraph quantDias = new Paragraph("Sugestão de compra para os próximos "+tb_diasEstoque.getText()+ " dias");    
             paragrafoNomeCli.setAlignment(Element.ALIGN_CENTER);
              relatorioSugestao.add(new Paragraph(quantDias)); 
              Paragraph margemSeguranca = new Paragraph("Margem de Segurança "+tb_margemSeguranca.getText()+ "%");    
             paragrafoNomeCli.setAlignment(Element.ALIGN_CENTER);
              relatorioSugestao.add(new Paragraph(margemSeguranca)); 
             relatorioSugestao.add(new Paragraph("\n"));
             PdfPTable tabela = new PdfPTable(3);
             PdfPCell header = new PdfPCell(new Paragraph("Relatório de Sugestão de Compras"));
            header.setColspan(3);
            tabela.addCell(header);	
        tabela.addCell("Codigo");
        tabela.addCell("Descrição");
        tabela.addCell("Quantidade Sugerida");
       
            
            for(Produto prod : objProdutoDAO.selecionarTodos())
            {
                if(prod.quantSugerida(Integer.parseInt(tb_diasEstoque.getText()), tb_margemSeguranca.getText())>0)
                {
                tabela.addCell(Integer.toString(prod.getCodigo()));
                tabela.addCell(prod.getDescricao());
                tabela.addCell(Integer.toString(prod.quantSugerida(Integer.parseInt(tb_diasEstoque.getText()), tb_margemSeguranca.getText())));
                }
                
            }
          
            
            relatorioSugestao.add(tabela);
            Runtime.getRuntime().exec (new String[]{"cmd.exe", "/c", "start", "C:\\relatoriosBeautySystem\\relatorioSugestao.pdf"}); 
            }
            catch(DocumentException de){
            de.printStackTrace();
        }catch(IOException ioe){
            ioe.printStackTrace();
        }finally{
            relatorioSugestao.close();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Rel_Sugestao_Compras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Rel_Sugestao_Compras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Rel_Sugestao_Compras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Rel_Sugestao_Compras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_Rel_Sugestao_Compras(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField tb_diasEstoque;
    private javax.swing.JTextField tb_margemSeguranca;
    // End of variables declaration//GEN-END:variables
}
