/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import entidade.Agendamento;
import java.awt.HeadlessException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Mello_PC
 */
public class Frm_Modificar_Status extends javax.swing.JFrame {

    /**
     * Creates new form Frm_Modificar_Status
     */
    JFrame parent;
    Agendamento objAgendamento = new Agendamento();
    private dao.AgendamentoDAO objAgendamentoDAO = new dao.AgendamentoDAO();
    int op;
    Frm_Modificar_Status(Agendamento objAgendamentoPesq, JFrame consAgendamento, int flag) {
        initComponents();
        setLocationRelativeTo(null);
        objAgendamento = objAgendamentoPesq;
        parent = consAgendamento;
       op = flag;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cb_statusAgendamento = new javax.swing.JComboBox();
        tb_observacaoText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        bt_modificaStatus = new javax.swing.JButton();
        tb_Cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("BrautySystem - Modificação de Status");

        cb_statusAgendamento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Realizado", "Cancelado", "Agendado", "Não Compareceu" }));

        jLabel1.setText("Observação:");

        bt_modificaStatus.setText("Modificar");
        bt_modificaStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_modificaStatusActionPerformed(evt);
            }
        });

        tb_Cancelar.setText("Cancelar");
        tb_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_CancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cb_statusAgendamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tb_observacaoText, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bt_modificaStatus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tb_Cancelar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_statusAgendamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tb_observacaoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_modificaStatus)
                    .addComponent(tb_Cancelar))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void cancelar()
        {
            if(javax.swing.JOptionPane.showConfirmDialog(null,"Deseja Cancelar a Operacao?","ATENÇÂO ",javax.swing.JOptionPane.YES_NO_OPTION)==0)
            {
                dispose();
            }
        }
    private void tb_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_CancelarActionPerformed
        cancelar();
    }//GEN-LAST:event_tb_CancelarActionPerformed
    private void popularAtributos()
            {
                objAgendamento.setStatus(String.valueOf(cb_statusAgendamento.getSelectedItem()));
                objAgendamento.setObservacao(tb_observacaoText.getText());
            }
    private void bt_modificaStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_modificaStatusActionPerformed
       popularAtributos();
       if(op==1)
       try{
            popularAtributos();
            objAgendamentoDAO.editar(objAgendamento);
            JOptionPane.showMessageDialog(this, "Agendamento modificado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            Frm_Cons_Agendamento f1 = (Frm_Cons_Agendamento)parent;
            f1.atualizaTabela();
            f1.setVisible(true);
            dispose();
            }
            catch (NumberFormatException | HeadlessException e){
            JOptionPane.showMessageDialog(this, "Erro"+e);
        }
       else if (op==2)
       {
           try{
            popularAtributos();
            objAgendamentoDAO.editar(objAgendamento);
            JOptionPane.showMessageDialog(this, "Agendamento modificado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            Frm_Agendamentos_Retroativos f1 = (Frm_Agendamentos_Retroativos)parent;
            f1.atualizaTabela();
            f1.setVisible(true);
            dispose();
            }
            catch (NumberFormatException | HeadlessException e){
            JOptionPane.showMessageDialog(this, "Erro"+e);
        }
       }
       
    }//GEN-LAST:event_bt_modificaStatusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Modificar_Status.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Modificar_Status.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Modificar_Status.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Modificar_Status.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_Modificar_Status(null, null,0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_modificaStatus;
    private javax.swing.JComboBox cb_statusAgendamento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton tb_Cancelar;
    private javax.swing.JTextField tb_observacaoText;
    // End of variables declaration//GEN-END:variables
}
