/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Timer;
import java.util.TimerTask;
import entidade.Agendamento;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import 

/**
 *
 * @author Mello_PC
 */
public class Frm_Gerenciamento_SMS extends javax.swing.JFrame implements ActionListener {
        javax.swing.Timer myTimer  = new javax.swing.Timer(1000, (ActionListener) this);
        Agendamento objAgendamento = new Agendamento();
        private List <entidade.Agendamento> agendamentos = new ArrayList();
        Calendar calendar = new GregorianCalendar(); 
        SimpleDateFormat formatadorHora = new SimpleDateFormat("HH:mm");
        SimpleDateFormat formatadorData = new SimpleDateFormat("yyyy-MM-dd");
        private DefaultTableModel modelo = new DefaultTableModel();
        private dao.AgendamentoDAO objAgendamentoDAO = new dao.AgendamentoDAO(); 
       
        int secondsPassed=5;
        
    /**
     * Creates new form Frm_Gerenciamento_SMS
     */
    public Frm_Gerenciamento_SMS() {
        
        myTimer.start();
        initComponents();
        
    }
        public void actionPerformed(ActionEvent e) {
        lb_statusEnvio.setText("Verificando em: "+secondsPassed--);
        if (secondsPassed == -1) 
        {
            lb_statusEnvio.setText("Consultando Agendamentos... ");
            agendamentos = objAgendamentoDAO.consultarAgendamentoEnvioSMS(formatadorData.format(calendar.getTime()),formatadorHora.format(calendar.getTime()));
            if(agendamentos.size()>0)
            {
                modelo = (DefaultTableModel)tblAgendamentoSMS.getModel();
                while(modelo.getRowCount()>0){
                    modelo.removeRow(0);
                }
                agendamentos.stream().forEach((p) -> {
                    modelo.addRow(new Object[] {p.getCodigo(), p.getCliente().getNome(), p.getHoraInicial(), p.getHoraFinal(), null});
                
                });
            }
            else
            {
                lb_statusEnvio.setText("Nenhum Agendamento Encontrado... ");
            }
         secondsPassed=5;   
        } 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbl_agendamentos = new javax.swing.JScrollPane();
        tblAgendamentoSMS = new javax.swing.JTable();
        lb_statusEnvio = new javax.swing.JLabel();
        bt_reenviarAgendamento = new javax.swing.JButton();
        bt_cancelamentoEnvio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("BeautySystem - Gerenciamento de Envio de SMS");

        tblAgendamentoSMS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Cód.", "Cliente", "Hora Inicial", "Hora Final", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbl_agendamentos.setViewportView(tblAgendamentoSMS);

        bt_reenviarAgendamento.setText("Reenviar");

        bt_cancelamentoEnvio.setText("Não Enviar");
        bt_cancelamentoEnvio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cancelamentoEnvioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bt_reenviarAgendamento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_cancelamentoEnvio)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tbl_agendamentos, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lb_statusEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tbl_agendamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_statusEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_reenviarAgendamento)
                    .addComponent(bt_cancelamentoEnvio))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    
   
    private void bt_cancelamentoEnvioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cancelamentoEnvioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_cancelamentoEnvioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Gerenciamento_SMS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Gerenciamento_SMS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Gerenciamento_SMS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Gerenciamento_SMS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_Gerenciamento_SMS().setVisible(true);
               
            }
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_cancelamentoEnvio;
    private javax.swing.JButton bt_reenviarAgendamento;
    private javax.swing.JLabel lb_statusEnvio;
    private javax.swing.JTable tblAgendamentoSMS;
    private javax.swing.JScrollPane tbl_agendamentos;
    // End of variables declaration//GEN-END:variables
}
