/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import javax.swing.JFrame;
import entidade.Cliente;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class Frm_Cons_Cliente2 extends javax.swing.JFrame {

    Cliente objCliente = new Cliente();
    private dao.ClienteDAO objClienteDAO = new dao.ClienteDAO();
    private List<entidade.Cliente> clientes = new ArrayList();
    private JFrame parent;
    private DefaultTableModel modelo = new DefaultTableModel();
    int op;
    public Frm_Cons_Cliente2(JFrame cadCli, int op) {
        initComponents();
        setLocationRelativeTo(null);
        this.parent = cadCli;
        this.op = op;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        rb_cliNome = new javax.swing.JRadioButton();
        rb_cliCodigo = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblresultado = new javax.swing.JTable();
        labelPesquisa = new javax.swing.JLabel();
        tb_txtPesquisa = new javax.swing.JTextField();
        bt_pesquisar = new javax.swing.JButton();
        bt_inserirCli = new javax.swing.JButton();
        bt_excluir_Cli = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("BeautySystem - Pesquisa de Clientes");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisa por:"));

        buttonGroup1.add(rb_cliNome);
        rb_cliNome.setText("Nome");

        buttonGroup1.add(rb_cliCodigo);
        rb_cliCodigo.setText("Código");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(rb_cliNome)
                .addGap(35, 35, 35)
                .addComponent(rb_cliCodigo))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb_cliNome)
                    .addComponent(rb_cliCodigo))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jScrollPane1.setToolTipText("");
        jScrollPane1.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                jScrollPane1ComponentRemoved(evt);
            }
        });
        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        tblresultado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "CPF"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblresultado);

        labelPesquisa.setText("Pesquisa:");
        labelPesquisa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                labelPesquisaFocusLost(evt);
            }
        });

        bt_pesquisar.setText("Pesquisar");
        bt_pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_pesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(labelPesquisa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tb_txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bt_pesquisar)))
                .addGap(0, 20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tb_txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bt_pesquisar))
                            .addComponent(labelPesquisa))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                .addContainerGap())
        );

        bt_inserirCli.setText("Inserir");
        bt_inserirCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_inserirCliActionPerformed(evt);
            }
        });

        bt_excluir_Cli.setText("Cancelar");
        bt_excluir_Cli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_excluir_CliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bt_inserirCli)
                        .addGap(18, 18, 18)
                        .addComponent(bt_excluir_Cli)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_inserirCli)
                    .addComponent(bt_excluir_Cli))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jScrollPane1ComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jScrollPane1ComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1ComponentRemoved

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void labelPesquisaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_labelPesquisaFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_labelPesquisaFocusLost

    private void bt_pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_pesquisarActionPerformed
        if (!tb_txtPesquisa.getText().equals("")){
          
           if(rb_cliNome.isSelected())
            {
                clientes = objClienteDAO.consultar("Nome", tb_txtPesquisa.getText(), 3);
                if (clientes.size()>0){
                    modelo = (DefaultTableModel)tblresultado.getModel();
                    while(modelo.getRowCount()>0){
                        modelo.removeRow(0);
                    }
                    clientes.stream().forEach((p) -> {
                        modelo.addRow(new Object[] {p.getCodigo(),p.getNome(), p.getCpf()});
                    });
                }
                else {
                    JOptionPane.showMessageDialog(this, "Nenhum registro encontrado!", "Informação", JOptionPane.INFORMATION_MESSAGE);
                }
            }
            
            else if( rb_cliCodigo.isSelected())
            {
                clientes = objClienteDAO.consultar("IdCliente", tb_txtPesquisa.getText(), 3);
                if (clientes.size()>0){
                    modelo = (DefaultTableModel)tblresultado.getModel();
                    while(modelo.getRowCount()>0){
                        modelo.removeRow(0);
                    }
                    clientes.stream().forEach((p) -> {
                        modelo.addRow(new Object[] {p.getCodigo(),p.getNome(), p.getCpf()});
                    });
                }
                else {
                    JOptionPane.showMessageDialog(this, "Nenhum registro encontrado!", "Informação", JOptionPane.INFORMATION_MESSAGE);
                }
            }
            // TODO add your handling code here:
        }
        else {
            JOptionPane.showMessageDialog(this, "Informe o valor da pesquisa!", "Erro!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bt_pesquisarActionPerformed

    private void bt_inserirCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_inserirCliActionPerformed
        int index = tblresultado.getSelectedRow();
        objCliente.setCodigo(clientes.get(index).getCodigo());
        objCliente.setNome(clientes.get(index).getNome());
        objCliente.setSituacao(clientes.get(index).getSituacao());
        if(objCliente.getSituacao().equals("Bloqueado"))
        {
            JOptionPane.showMessageDialog(this,"Cliente Bloqueado, não será possível a operação!","Atenção!", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            if (op==1)
            {
        Frm_Realizar_Venda f1 = (Frm_Realizar_Venda)parent;
        f1.setTb_Cliente(Integer.toString(clientes.get(index).getCodigo()), objCliente);
        f1.setVisible(true);
        dispose();
            }
            else if(op==2)
            {
                Frm_Realizar_Agendamento f1 = (Frm_Realizar_Agendamento)parent;
        f1.setTb_Cliente(Integer.toString(clientes.get(index).getCodigo()));
        f1.setVisible(true);
        dispose();
            }
            else if(op==3){
                    Frm_Cons_Agendamento f1 = (Frm_Cons_Agendamento)parent;
        f1.setTb_Cliente(Integer.toString(clientes.get(index).getCodigo()));
        f1.setVisible(true);
        dispose();
            }
            else if(op==4){
                    Frm_Rel_Clientes f1 = (Frm_Rel_Clientes)parent;
        f1.setTb_codiCli(Integer.toString(clientes.get(index).getCodigo()));
        f1.setVisible(true);
        dispose();
            }
            }
        
    }//GEN-LAST:event_bt_inserirCliActionPerformed

    private void bt_excluir_CliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_excluir_CliActionPerformed
       dispose();

    }//GEN-LAST:event_bt_excluir_CliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Cons_Cliente2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Cons_Cliente2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Cons_Cliente2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Cons_Cliente2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_Cons_Cliente2(null,0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_excluir_Cli;
    private javax.swing.JButton bt_inserirCli;
    private javax.swing.JButton bt_pesquisar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelPesquisa;
    private javax.swing.JRadioButton rb_cliCodigo;
    private javax.swing.JRadioButton rb_cliNome;
    private javax.swing.JTextField tb_txtPesquisa;
    private javax.swing.JTable tblresultado;
    // End of variables declaration//GEN-END:variables
}
