/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import entidade.GrupoProdutos;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mello_PC
 */
public class Frm_Cons_GrupoPro extends javax.swing.JFrame {

    GrupoProdutos objGrupoProdutos = new GrupoProdutos();
    private dao.GrupoProdutosDAO objGrupoProdutosDAO = new dao.GrupoProdutosDAO();
    private DefaultTableModel modelo = new DefaultTableModel();
    private List<entidade.GrupoProdutos> grupoprodutos = new ArrayList();
    public Frm_Cons_GrupoPro() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        rb_descricaoGp = new javax.swing.JRadioButton();
        rb_ncmGp = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblresultado = new javax.swing.JTable();
        bt_alterarFunc = new javax.swing.JButton();
        bt_excluirFunc = new javax.swing.JToggleButton();
        tb_txtPesquisa = new javax.swing.JTextField();
        bt_pesquisar = new javax.swing.JButton();
        bt_sair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("BeautySystem - Consulta de Grupo de Produtos");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisa por:"));

        buttonGroup1.add(rb_descricaoGp);
        rb_descricaoGp.setText("Descrição");

        buttonGroup1.add(rb_ncmGp);
        rb_ncmGp.setText("N.C.M");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rb_descricaoGp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rb_ncmGp)
                .addGap(49, 49, 49))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb_descricaoGp)
                    .addComponent(rb_ncmGp))
                .addGap(0, 7, Short.MAX_VALUE))
        );

        tblresultado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Descrição", "N.C.M"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblresultado);

        bt_alterarFunc.setText("Alterar");
        bt_alterarFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_alterarFuncActionPerformed(evt);
            }
        });

        bt_excluirFunc.setText("Excluir");
        bt_excluirFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_excluirFuncActionPerformed(evt);
            }
        });

        bt_pesquisar.setText("Pesquisar");
        bt_pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_pesquisarActionPerformed(evt);
            }
        });

        bt_sair.setText("Sair");
        bt_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_sairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tb_txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt_pesquisar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bt_alterarFunc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt_excluirFunc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt_sair)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tb_txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_pesquisar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_alterarFunc)
                    .addComponent(bt_excluirFunc)
                    .addComponent(bt_sair))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void bt_alterarFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_alterarFuncActionPerformed
    try
    {
        int index = tblresultado.getSelectedRow();
        objGrupoProdutos.setCodigo(grupoprodutos.get(index).getCodigo());
        objGrupoProdutos.setDescricao(grupoprodutos.get(index).getDescricao());
        objGrupoProdutos.setNcm(grupoprodutos.get(index).getNcm());
        Frm_Alt_GrupoPro f1 = new Frm_Alt_GrupoPro(objGrupoProdutos);
        f1.setVisible(true);
        dispose();
    }
    catch(Exception e)
    {
        JOptionPane.showMessageDialog(this, "Registro não selecionado!", "Erro:", JOptionPane.INFORMATION_MESSAGE);
    }
    }//GEN-LAST:event_bt_alterarFuncActionPerformed

    private void bt_pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_pesquisarActionPerformed
     if (!tb_txtPesquisa.getText().equals("")){
            if(rb_descricaoGp.isSelected())
            {
                grupoprodutos = objGrupoProdutosDAO.consultar("Descricao", tb_txtPesquisa.getText(), 1);
                if (grupoprodutos.size()>0){
                    modelo = (DefaultTableModel)tblresultado.getModel();
                    while(modelo.getRowCount()>0){
                        modelo.removeRow(0);
                    }
                    grupoprodutos.stream().forEach((p) -> {
                        modelo.addRow(new Object[] {p.getDescricao(),p.getNcm()});
                    });
                }
                else {
                    JOptionPane.showMessageDialog(this, "Nenhum registro encontrado!", "Informação", JOptionPane.INFORMATION_MESSAGE);
                }
            }
            else if(rb_ncmGp.isSelected())
            {
                grupoprodutos = objGrupoProdutosDAO.consultar("NCM", tb_txtPesquisa.getText(), 1);
                if (grupoprodutos.size()>0){
                    modelo = (DefaultTableModel)tblresultado.getModel();
                    while(modelo.getRowCount()>0){
                        modelo.removeRow(0);
                    }
                    grupoprodutos.stream().forEach((p) -> {
                        modelo.addRow(new Object[] {p.getDescricao(),p.getNcm()});
                    });
                }
                else {
                    JOptionPane.showMessageDialog(this, "Nenhum registro encontrado!", "Informação", JOptionPane.INFORMATION_MESSAGE);
                }
            }
            
            else {
                JOptionPane.showMessageDialog(this, "Selecione um dos Filtros de Pesquisa","Aviso",JOptionPane.INFORMATION_MESSAGE);
            }
      }
      else {
            JOptionPane.showMessageDialog(this, "Informe o valor da pesquisa!", "Erro!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bt_pesquisarActionPerformed

    private void bt_excluirFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_excluirFuncActionPerformed
      if(javax.swing.JOptionPane.showConfirmDialog(null,"Deseja Excluir o grupo de produtos selecionado?","ATENÇÂO ",javax.swing.JOptionPane.YES_NO_OPTION )==0)
        {
        try{
        int index = tblresultado.getSelectedRow();
        objGrupoProdutos.setCodigo(grupoprodutos.get(index).getCodigo());
        objGrupoProdutosDAO.excluir(objGrupoProdutos);
        JOptionPane.showMessageDialog(this, "Registro excluido com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
        grupoprodutos.remove(index);
        modelo.removeRow(index);
        }
        
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, "Registro não selecionado!", "Erro:", JOptionPane.INFORMATION_MESSAGE);
        }
        }
    }//GEN-LAST:event_bt_excluirFuncActionPerformed

    private void bt_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_sairActionPerformed
        dispose();
    }//GEN-LAST:event_bt_sairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Cons_GrupoPro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Cons_GrupoPro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Cons_GrupoPro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Cons_GrupoPro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_Cons_GrupoPro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_alterarFunc;
    private javax.swing.JToggleButton bt_excluirFunc;
    private javax.swing.JButton bt_pesquisar;
    private javax.swing.JButton bt_sair;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rb_descricaoGp;
    private javax.swing.JRadioButton rb_ncmGp;
    private javax.swing.JTextField tb_txtPesquisa;
    private javax.swing.JTable tblresultado;
    // End of variables declaration//GEN-END:variables
}
