/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import entidade.Cliente;
import entidade.Funcionario;
import entidade.Venda;
import entidade.Produto;
import java.awt.HeadlessException;
import java.text.ParseException;
import java.util.Calendar;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Image;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import java.io.File;
public class Frm_Realizar_Venda extends javax.swing.JFrame {

     Produto objProduto = new entidade.Produto();
   Venda objVenda = new Venda();
   Cliente objCliente = new Cliente();
   Funcionario objFuncionario = new Funcionario();
   private dao.ClienteDAO objClienteDAO = new dao.ClienteDAO();
   private dao.FuncionarioDAO objFuncionarioDAO = new dao.FuncionarioDAO();
    private dao.ProdutoDAO objProdutoDAO = new dao.ProdutoDAO();
    private final dao.VendaDAO objVendaDAO = new dao.VendaDAO();
     private DefaultTableModel modelo = new DefaultTableModel();
     private List <entidade.Produto> produtos = new ArrayList();
     Calendar calendar = new GregorianCalendar();  
    Date date = new Date();
    SimpleDateFormat formatador = new SimpleDateFormat("dd/MM/yyyy"); 
    public Frm_Realizar_Venda(Venda objVendaPesq, int op) {
        initComponents();
        setLocationRelativeTo(null); 
        if(op == 1)
        {
            tb_codigoVenda.setText(Integer.toString(objVendaPesq.getCodigo()));
            objVenda.setCodigo(objVendaPesq.getCodigo());
            date = objVendaPesq.getDataVenda();
            tb_dataVenda.setText(formatador.format(date));
            tb_clienteVenda.setText(Integer.toString(objVendaPesq.getCliente().getCodigo()));
            tb_FuncionarioVenda.setText(Integer.toString(objVendaPesq.getFuncionario().getCodigo()));
            objVenda.setValorVenda(objVendaPesq.getValorVenda());
            lb_valorParcialVenda.setText(Double.toString(objVendaPesq.getValorVenda()));
            produtos = objVendaPesq.getProdutos();
            objVenda.setProdutos(produtos);
            bt_cancelar1.setVisible(false);
            bt_cancelar.setVisible(false);
            bt_finalizar.setVisible(false);
            bt_inserir.setVisible(false);
            bt_inserirItem.setVisible(false);
            bt_pesquisaPro.setVisible(false);
            bt_pesquisarCliente.setVisible(false);
            bt_pesquisarFuncionario.setVisible(false);
            bt_removeItem.setVisible(false);
            if(produtos.size()>0)
            {
             modelo = (DefaultTableModel)tblprodutos.getModel();
                    while(modelo.getRowCount()>0){
                        modelo.removeRow(0);
         }
                    produtos.stream().forEach((p) -> {
                        modelo.addRow(new Object[] {p.getCodigo(),p.getDescricao(), p.getQuantidade(),p.getValorCompra()});
                    });
            }
        }
        else{
        calendar.setTime(date); 
        tb_dataVenda.setText(formatador.format(calendar.getTime()));
        tb_codigoVenda.setText(Integer.toString(objVendaDAO.retornaCodigo()));
        objVenda.setCodigo(objVendaDAO.retornaCodigo());
        bt_Fechar.setVisible(false);
            }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        JTab = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        tb_dataVenda = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        bt_pesquisarCliente = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tb_clienteVenda = new javax.swing.JTextField();
        lb_nomeCliente = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tb_FuncionarioVenda = new javax.swing.JTextField();
        bt_pesquisarFuncionario = new javax.swing.JButton();
        lb_nomeFuncionario = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lb_valorParcialVenda = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblprodutos = new javax.swing.JTable();
        bt_inserir = new javax.swing.JButton();
        bt_finalizar = new javax.swing.JButton();
        bt_cancelar = new javax.swing.JButton();
        bt_removeItem = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        tb_codigoVenda = new javax.swing.JTextField();
        bt_Fechar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        bt_pesquisaPro = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        tb_codigoPro = new javax.swing.JTextField();
        tb_quantidade = new javax.swing.JTextField();
        tb_valorItem = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        bt_inserirItem = new javax.swing.JButton();
        bt_cancelar1 = new javax.swing.JButton();
        lb_descricao = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("BeautySystem - Realizar Venda");

        tb_dataVenda.setEditable(false);
        tb_dataVenda.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        jLabel1.setText("Data da Venda:");

        bt_pesquisarCliente.setText("Pesquisar...");
        bt_pesquisarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_pesquisarClienteActionPerformed(evt);
            }
        });

        jLabel2.setText("Cliente:");

        tb_clienteVenda.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tb_clienteVendaFocusLost(evt);
            }
        });

        jLabel4.setText("Funcionário:");

        tb_FuncionarioVenda.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tb_FuncionarioVendaFocusLost(evt);
            }
        });

        bt_pesquisarFuncionario.setText("Pesquisar...");
        bt_pesquisarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_pesquisarFuncionarioActionPerformed(evt);
            }
        });

        jLabel3.setText("Valor Parcial da Venda:");

        tblprodutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Descrição", "Quantidade", "Valor de Venda"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblprodutos);

        bt_inserir.setText("Inserir Ítem");
        bt_inserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_inserirActionPerformed(evt);
            }
        });

        bt_finalizar.setText("Finalizar Venda");
        bt_finalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_finalizarActionPerformed(evt);
            }
        });

        bt_cancelar.setText("Cancelar Venda");
        bt_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cancelarActionPerformed(evt);
            }
        });

        bt_removeItem.setText("Remover Item");
        bt_removeItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_removeItemActionPerformed(evt);
            }
        });

        jLabel5.setText("Código da Venda:");

        tb_codigoVenda.setEditable(false);

        bt_Fechar.setText("Fechar");
        bt_Fechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_FecharActionPerformed(evt);
            }
        });

        jLabel9.setText("Lista de Ítens");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tb_codigoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tb_dataVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tb_clienteVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_pesquisarCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_nomeCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tb_FuncionarioVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_pesquisarFuncionario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_nomeFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(167, 167, 167)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lb_valorParcialVenda))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(bt_inserir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt_finalizar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt_cancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bt_removeItem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt_Fechar)))
                        .addGap(0, 12, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tb_dataVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(tb_codigoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(tb_clienteVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bt_pesquisarCliente))
                    .addComponent(lb_nomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tb_FuncionarioVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_pesquisarFuncionario)
                    .addComponent(lb_nomeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lb_valorParcialVenda)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_inserir)
                    .addComponent(bt_finalizar)
                    .addComponent(bt_cancelar)
                    .addComponent(bt_removeItem)
                    .addComponent(bt_Fechar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JTab.addTab("Venda", jPanel1);

        jPanel2.setEnabled(false);

        bt_pesquisaPro.setText("Pesquisar...");
        bt_pesquisaPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_pesquisaProActionPerformed(evt);
            }
        });

        jLabel6.setText("Código do Produto:");

        tb_codigoPro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tb_codigoProFocusLost(evt);
            }
        });

        tb_quantidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tb_quantidadeFocusLost(evt);
            }
        });

        tb_valorItem.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tb_valorItemFocusLost(evt);
            }
        });

        jLabel8.setText("Valor de Venda:");

        jLabel7.setText("Quantidade:");

        bt_inserirItem.setText("Inserir");
        bt_inserirItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_inserirItemActionPerformed(evt);
            }
        });

        bt_cancelar1.setText("Cancelar");
        bt_cancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cancelar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tb_valorItem))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tb_codigoPro, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_pesquisaPro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_descricao, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tb_quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(bt_inserirItem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt_cancelar1)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tb_codigoPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_pesquisaPro)
                    .addComponent(lb_descricao, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tb_quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tb_valorItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_inserirItem)
                    .addComponent(bt_cancelar1))
                .addGap(0, 167, Short.MAX_VALUE))
        );

        JTab.addTab("Inserção de Itens", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JTab)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JTab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_pesquisarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_pesquisarFuncionarioActionPerformed
        Frm_Cons_Func_Venda f1= new Frm_Cons_Func_Venda(Frm_Realizar_Venda.this,1);
        f1.setVisible(true);
    }//GEN-LAST:event_bt_pesquisarFuncionarioActionPerformed

    private void bt_pesquisarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_pesquisarClienteActionPerformed
        Frm_Cons_Cliente2 f1= new Frm_Cons_Cliente2(Frm_Realizar_Venda.this,1);
        f1.setVisible(true);
    }//GEN-LAST:event_bt_pesquisarClienteActionPerformed

    private void bt_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cancelarActionPerformed
        cancelar();
    }//GEN-LAST:event_bt_cancelarActionPerformed

    private void bt_inserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_inserirActionPerformed
     if (tb_clienteVenda.getText().equals("") || tb_FuncionarioVenda.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Preencha os campos relacionados a venda!", "Informação", JOptionPane.INFORMATION_MESSAGE);
        }
     else 
     {
         JTab.setSelectedIndex(1);
     }
                
    }//GEN-LAST:event_bt_inserirActionPerformed

    private void bt_pesquisaProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_pesquisaProActionPerformed
        Frm_Cons_Pro2 f1 = new Frm_Cons_Pro2(Frm_Realizar_Venda.this,2);
        f1.setVisible(true);
    }//GEN-LAST:event_bt_pesquisaProActionPerformed

    private boolean verificarEstoque()
    {
        if(Integer.valueOf(tb_quantidade.getText())>objProduto.retornaEstoque())
        {
            return false;
           
        }
        else
        {
            return true;
            
        }
       
    }
    private void bt_inserirItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_inserirItemActionPerformed
        if (tb_clienteVenda.getText().equals("") || tb_FuncionarioVenda.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Preencha os campos relacionados ao produto!", "Informação", JOptionPane.INFORMATION_MESSAGE);
        }
        else
        {
            if(verificarEstoque())
            {
                if(Double.valueOf(tb_valorItem.getText().replace(",", "."))!= objProduto.getValorVenda())
            {
                objProduto.setValorVenda(Double.valueOf(tb_valorItem.getText().replace(",", ".")));
                objProdutoDAO.editar(objProduto);
            }
            objVenda.getProdutos().add(objProduto);
            modelo = (DefaultTableModel)tblprodutos.getModel();
            modelo.addRow(new Object[]{objProduto.getCodigo(), objProduto.getDescricao(), objProduto.getQuantidade(), objProduto.getValorVenda()});
            objVenda.setValorVenda(objVenda.getValorVenda()+(Integer.valueOf(tb_quantidade.getText())* Double.valueOf(tb_valorItem.getText().replace(",", "."))));
            lb_valorParcialVenda.setText(Double.toString(objVenda.getValorVenda()));
            JTab.setSelectedIndex(0);
            tb_codigoPro.setText("");
            tb_quantidade.setText("");
            tb_valorItem.setText("");
            lb_descricao.setText("");
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Quantidade informada ("+tb_quantidade.getText()+") é maior do que estoque ("+objProduto.retornaEstoque()+")", "Informação", JOptionPane.INFORMATION_MESSAGE);
                tb_codigoPro.requestFocus();
            }
        }
    }//GEN-LAST:event_bt_inserirItemActionPerformed

    private void bt_cancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cancelar1ActionPerformed
       JTab.setSelectedIndex(0);
        tb_codigoPro.setText("");
        tb_quantidade.setText("");
        tb_valorItem.setText("");
        lb_descricao.setText("");
        
    }//GEN-LAST:event_bt_cancelar1ActionPerformed

    private void bt_removeItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_removeItemActionPerformed
      int index = tblprodutos.getSelectedRow();
        modelo = (DefaultTableModel)tblprodutos.getModel();
        double valorProdutoRemocao = objVenda.getProdutos().get(index).getValorVenda();
      int quantValorRemov = objVenda.getProdutos().get(index).getQuantidade();
      modelo.removeRow(index);
        objVenda.getProdutos().remove(index);
         objVenda.setValorVenda(objVenda.getValorVenda()-(quantValorRemov * valorProdutoRemocao));
         lb_valorParcialVenda.setText(Double.toString(objVenda.getValorVenda()));
    }//GEN-LAST:event_bt_removeItemActionPerformed

     private void popularAtributos() throws ParseException
    {
      SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");  
        java.sql.Date data = new java.sql.Date(format.parse(tb_dataVenda.getText()).getTime()); 
        objVenda.setDataVenda(data);
        objVenda.setMotivo(null);
        objVenda.setEstorno("N");
       
    }
    private void tb_quantidadeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tb_quantidadeFocusLost
        objProduto.setQuantidade(Integer.parseInt(tb_quantidade.getText()));
        if (!verificarEstoque())
        {
            JOptionPane.showMessageDialog(this, "Quantidade informada ("+tb_quantidade.getText()+") é maior do que estoque ("+objProduto.retornaEstoque()+")", "Informação", JOptionPane.INFORMATION_MESSAGE);
                tb_codigoPro.requestFocus();
        }
    }//GEN-LAST:event_tb_quantidadeFocusLost

    private void tb_valorItemFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tb_valorItemFocusLost
     objProduto.setValorVenda(Double.parseDouble(tb_valorItem.getText()));
    }//GEN-LAST:event_tb_valorItemFocusLost

    private void bt_finalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_finalizarActionPerformed
    try{
        
        
            popularAtributos();
            objVendaDAO.gravar(objVenda);
            JOptionPane.showMessageDialog(this, "Registro inserido com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            if(javax.swing.JOptionPane.showConfirmDialog(null,"Deseja Imprimir Comprovante de Venda?","Mensagem: ",javax.swing.JOptionPane.YES_NO_OPTION )==0){
            gerarRelatorioVenda();
            
        }
            
            
              
            dispose();
        } catch (NumberFormatException | HeadlessException e){
            JOptionPane.showMessageDialog(this, "Erro"+e);
        } catch (ParseException ex) {
            Logger.getLogger(Frm_Realizar_Compra.class.getName()).log(Level.SEVERE, null, ex);
        } 
    
    }//GEN-LAST:event_bt_finalizarActionPerformed
private void criaDiretorio(String novoDiretorio){  
    String nomeDiretorio = null;   
    String separador = java.io.File.separator;   
    try {       
         nomeDiretorio = "C:" + separador + novoDiretorio;   
         if (!new File(nomeDiretorio).exists()) { // Verifica se o diretório existe.   
             (new File(nomeDiretorio)).mkdir();   // Cria o diretório   
         }   
    } catch (Exception ex) {   
         JOptionPane.showMessageDialog(null,"Err","Erro ao criar o diretório" + ex.toString(),JOptionPane.ERROR_MESSAGE);   
    }  
}  
    private void gerarRelatorioVenda()
    {
        criaDiretorio("relatoriosBeautySystem");
        Document comprovanteVenda = new Document(PageSize.A4);
            try{
            PdfWriter.getInstance(comprovanteVenda, new FileOutputStream("C:\\relatoriosBeautySystem\\ComprovanteVenda.pdf"));
            comprovanteVenda.open();
            Paragraph paragrafo = new Paragraph("Comprovante de Venda");    
             paragrafo.setAlignment(Element.ALIGN_CENTER);
            comprovanteVenda.add(new Paragraph(paragrafo));
            Paragraph paragrafoNomeCli = new Paragraph("Nome do Cliente: "+objVenda.getCliente().getNome());    
             paragrafoNomeCli.setAlignment(Element.ALIGN_CENTER);
             comprovanteVenda.add(paragrafoNomeCli);
             Paragraph paragrafocodiVen = new Paragraph("Código da Venda: "+objVenda.getCodigo());    
             paragrafocodiVen.setAlignment(Element.ALIGN_CENTER);
             comprovanteVenda.add(paragrafocodiVen); 
             Paragraph paragrafodataVen = new Paragraph("Data da Venda: "+tb_dataVenda.getText());    
             paragrafodataVen.setAlignment(Element.ALIGN_CENTER);
             comprovanteVenda.add(paragrafodataVen);
             Paragraph paragrafonomeFun = new Paragraph("Nome do Funcionario: "+objVenda.getFuncionario().getNome());    
             paragrafonomeFun.setAlignment(Element.ALIGN_CENTER);
             comprovanteVenda.add(paragrafonomeFun);
             comprovanteVenda.add(new Paragraph("\n"));
             PdfPTable tabela = new PdfPTable(4);
             PdfPCell header = new PdfPCell(new Paragraph("Lista de Ítens da Venda"));
            header.setColspan(4);
            tabela.addCell(header);	
        tabela.addCell("Codigo Item");
        tabela.addCell("Descrição");
        tabela.addCell("Quantidade");
        tabela.addCell("Valor");
       
            
            for(Produto prod :objVenda.getProdutos())
            {
                tabela.addCell(Integer.toString(prod.getCodigo()));
                tabela.addCell(prod.getDescricao());
                tabela.addCell(Integer.toString(prod.getQuantidade()));
                tabela.addCell(Double.toString(prod.getValorVenda()));

            }
            PdfPCell total = new PdfPCell(new Paragraph("Total"));
            total.setColspan(3);
            tabela.addCell(total);
            tabela.addCell(Double.toString(objVenda.getValorVenda()));
            
            comprovanteVenda.add(tabela);
            Runtime.getRuntime().exec (new String[]{"cmd.exe", "/c", "start", "C:\\relatoriosBeautySystem\\ComprovanteVenda.pdf"}); 
            }
            catch(DocumentException de){
            de.printStackTrace();
        }catch(IOException ioe){
            ioe.printStackTrace();
        }finally{
            comprovanteVenda.close();
        }
    }
    private void bt_FecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_FecharActionPerformed
    dispose();
    }//GEN-LAST:event_bt_FecharActionPerformed

    private void tb_clienteVendaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tb_clienteVendaFocusLost
        objCliente = objClienteDAO.consultar(Long.parseLong(tb_clienteVenda.getText()));
        if(objCliente.getNome()== null)
        {
            JOptionPane.showMessageDialog(this, "Nenhum registro encontrado!", "Informação", JOptionPane.INFORMATION_MESSAGE);
            tb_clienteVenda.requestFocus();
            tb_clienteVenda.setText("");
            bt_inserir.setEnabled(false);
        }
        else if(objCliente.getSituacao().equals("Bloqueado"))
        {
            JOptionPane.showMessageDialog(this, "Cliente "+objCliente.getNome()+" Bloqueado!", "Informação", JOptionPane.INFORMATION_MESSAGE);
            tb_clienteVenda.requestFocus();
            tb_clienteVenda.setText("");
            lb_nomeCliente.setText("");
            bt_inserir.setEnabled(false);
        }
        else{
        lb_nomeCliente.setText(objCliente.getNome());
        tb_FuncionarioVenda.requestFocus();
        objVenda.setCliente(objCliente);
        bt_inserir.setEnabled(true);
        }
    }//GEN-LAST:event_tb_clienteVendaFocusLost

    private void tb_FuncionarioVendaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tb_FuncionarioVendaFocusLost
    objFuncionario = objFuncionarioDAO.consultar(Long.parseLong(tb_FuncionarioVenda.getText()));
    if(objFuncionario.getNome() == null)
    {
        JOptionPane.showMessageDialog(this, "Nenhum registro encontrado!", "Informação", JOptionPane.INFORMATION_MESSAGE);
        tb_FuncionarioVenda.requestFocus();
        tb_FuncionarioVenda.setText("");
    }
    else
    {
    lb_nomeFuncionario.setText(objFuncionario.getNome());    
    objVenda.setFuncionario(objFuncionario);
    bt_inserir.requestFocus();
    }
    }//GEN-LAST:event_tb_FuncionarioVendaFocusLost

    private void tb_codigoProFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tb_codigoProFocusLost
    objProduto = objProdutoDAO.consultar(Long.parseLong(tb_codigoPro.getText()));
    if(objProduto.getDescricao()!= null)
    {
    setlb_DescPro(objProduto.getDescricao());
    setTb_ValorItem(Double.toString(objProduto.getValorCompra()));
    tb_quantidade.requestFocus();
    }
    else
    {
        JOptionPane.showMessageDialog(this, "Nenhum registro encontrado!", "Informação", JOptionPane.INFORMATION_MESSAGE);
        tb_codigoPro.requestFocus();
        tb_codigoPro.setText("");
    }
    }//GEN-LAST:event_tb_codigoProFocusLost
    private void cancelar() {
       if(javax.swing.JOptionPane.showConfirmDialog(null,"Deseja Cancelar a Venda?","ATENÇÂO ",javax.swing.JOptionPane.YES_NO_OPTION )==0){  
            this.dispose();  
    }
    }    void setTb_Cliente(String conteudo, Cliente cliente)
    {
        tb_clienteVenda.setText(conteudo);
        lb_nomeCliente.setText(cliente.getNome());
        tb_clienteVenda.requestFocus();
        
    }
    void setTb_Funcionario(String conteudo, Funcionario funcionario)
    {
        tb_FuncionarioVenda.setText(conteudo);
        lb_nomeFuncionario.setText(funcionario.getNome());
        tb_FuncionarioVenda.requestFocus();
       
    }
     void setProduto(String conteudo, Produto produto)
    {
        tb_codigoPro.setText(conteudo);
        objProduto = produto;
    }
    
   void setlb_DescPro(String conteudo)
    {
        lb_descricao.setText(conteudo);
    }
    void setTb_ValorItem(String conteudo)
    {
        tb_valorItem.setText(conteudo);
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Realizar_Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Realizar_Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Realizar_Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Realizar_Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_Realizar_Venda(null, 0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane JTab;
    private javax.swing.JButton bt_Fechar;
    private javax.swing.JButton bt_cancelar;
    private javax.swing.JButton bt_cancelar1;
    private javax.swing.JButton bt_finalizar;
    private javax.swing.JButton bt_inserir;
    private javax.swing.JButton bt_inserirItem;
    private javax.swing.JButton bt_pesquisaPro;
    private javax.swing.JButton bt_pesquisarCliente;
    private javax.swing.JButton bt_pesquisarFuncionario;
    private javax.swing.JButton bt_removeItem;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_descricao;
    private javax.swing.JLabel lb_nomeCliente;
    private javax.swing.JLabel lb_nomeFuncionario;
    private javax.swing.JLabel lb_valorParcialVenda;
    private javax.swing.JTextField tb_FuncionarioVenda;
    private javax.swing.JTextField tb_clienteVenda;
    private javax.swing.JTextField tb_codigoPro;
    private javax.swing.JTextField tb_codigoVenda;
    private javax.swing.JFormattedTextField tb_dataVenda;
    private javax.swing.JTextField tb_quantidade;
    private javax.swing.JTextField tb_valorItem;
    private javax.swing.JTable tblprodutos;
    // End of variables declaration//GEN-END:variables

    
}
