/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import entidade.Produto;
import entidade.Venda;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Mello_PC
 */
public class Frm_Motivo_Estorno_Venda extends javax.swing.JFrame {

    Venda objVenda = new Venda();
    private JFrame parent;
    private dao.VendaDAO objVendaDAO = new dao.VendaDAO();
    public Frm_Motivo_Estorno_Venda(Venda objVenda, JFrame consVenda) {
        initComponents();
        setLocationRelativeTo(null);
        this.objVenda = objVenda;
        this.parent = consVenda;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tb_motivoEstornoVenda = new javax.swing.JTextField();
        bt_estornar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Motivo do Estorno de Venda");

        jLabel1.setText("Motivo:");

        bt_estornar.setText("Estornar");
        bt_estornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_estornarActionPerformed(evt);
            }
        });

        jButton1.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tb_motivoEstornoVenda))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bt_estornar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(0, 236, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tb_motivoEstornoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_estornar)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_estornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_estornarActionPerformed
            if(javax.swing.JOptionPane.showConfirmDialog(null,"Deseja Estornar a venda do cliente "+objVenda.getCliente().getNome()+" de "+objVenda.getValorVenda()+ "?","ATENÇÂO ",javax.swing.JOptionPane.YES_NO_OPTION )==0)
            {
                objVenda.setEstorno("S");
                objVenda.setMotivo(tb_motivoEstornoVenda.getText());
                objVendaDAO.editar(objVenda);
                JOptionPane.showMessageDialog(this, "Estorno Realizado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                Frm_Cons_Venda f1 = (Frm_Cons_Venda)parent;
                f1.atualizaTabela();
                f1.setVisible(true);
                if(javax.swing.JOptionPane.showConfirmDialog(null,"Deseja Imprimir Comprovante de Etorno?","Mensagem: ",javax.swing.JOptionPane.YES_NO_OPTION )==0){
            gerarRelatorioEstorno();
            }
                dispose();
            }
    }//GEN-LAST:event_bt_estornarActionPerformed
    private void criaDiretorio(String novoDiretorio){  
    String nomeDiretorio = null;   
    String separador = java.io.File.separator;   
    try {       
         nomeDiretorio = "C:" + separador + novoDiretorio;   
         if (!new File(nomeDiretorio).exists()) { // Verifica se o diretório existe.   
             (new File(nomeDiretorio)).mkdir();   // Cria o diretório   
         }   
    } catch (Exception ex) {   
         JOptionPane.showMessageDialog(null,"Err","Erro ao criar o diretório" + ex.toString(),JOptionPane.ERROR_MESSAGE);   
    }  
}
    private void gerarRelatorioEstorno()
    {
        
        criaDiretorio("relatoriosBeautySystem");
        Document comprovanteVenda = new Document(PageSize.A4);
            try{
            PdfWriter.getInstance(comprovanteVenda, new FileOutputStream("C:\\relatoriosBeautySystem\\ComprovanteEstorno.pdf"));
            comprovanteVenda.open();
            Paragraph paragrafo = new Paragraph("Comprovante de Estorno");    
             paragrafo.setAlignment(Element.ALIGN_CENTER);
            comprovanteVenda.add(new Paragraph(paragrafo));
            Paragraph paragrafoNomeCli = new Paragraph("Nome do Cliente: "+objVenda.getCliente().getNome());    
             paragrafoNomeCli.setAlignment(Element.ALIGN_CENTER);
             comprovanteVenda.add(paragrafoNomeCli);
             Paragraph paragrafocodiVen = new Paragraph("Código da Venda: "+objVenda.getCodigo());    
             paragrafocodiVen.setAlignment(Element.ALIGN_CENTER);
             comprovanteVenda.add(paragrafocodiVen); 
             Paragraph paragrafodataVen = new Paragraph("Data da Venda: "+objVenda.getDataVenda());    
             paragrafodataVen.setAlignment(Element.ALIGN_CENTER);
             comprovanteVenda.add(paragrafodataVen);
             Paragraph paragrafonomeFun = new Paragraph("Nome do Funcionario: "+objVenda.getFuncionario().getNome());    
             paragrafonomeFun.setAlignment(Element.ALIGN_CENTER);
             comprovanteVenda.add(paragrafonomeFun);
             comprovanteVenda.add(new Paragraph("\n"));
             PdfPTable tabela = new PdfPTable(4);
             PdfPCell header = new PdfPCell(new Paragraph("Lista de Ítens da Venda"));
            header.setColspan(4);
            tabela.addCell(header);	
        tabela.addCell("Codigo Item");
        tabela.addCell("Descrição");
        tabela.addCell("Quantidade");
        tabela.addCell("Valor");
       
            
            for(Produto prod :objVenda.getProdutos())
            {
                tabela.addCell(Integer.toString(prod.getCodigo()));
                tabela.addCell(prod.getDescricao());
                tabela.addCell(Integer.toString(prod.getQuantidade()));
                tabela.addCell(Double.toString(prod.getValorVenda()));

            }
            PdfPCell total = new PdfPCell(new Paragraph("Total"));
            total.setColspan(3);
            tabela.addCell(total);
            tabela.addCell(Double.toString(objVenda.getValorVenda()));
            
            comprovanteVenda.add(tabela);
            comprovanteVenda.add(new Paragraph("\n"));
            comprovanteVenda.add(new Paragraph("\n"));
            comprovanteVenda.add(new Paragraph("\n"));
            comprovanteVenda.add(new Paragraph("Motivo do Estorno: "+ objVenda.getMotivo()));
            Runtime.getRuntime().exec (new String[]{"cmd.exe", "/c", "start", "C:\\relatoriosBeautySystem\\ComprovanteEstorno.pdf"}); 
            }
            catch(DocumentException de){
            de.printStackTrace();
        }catch(IOException ioe){
            ioe.printStackTrace();
        }finally{
            comprovanteVenda.close();
            
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Motivo_Estorno_Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Motivo_Estorno_Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Motivo_Estorno_Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Motivo_Estorno_Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_Motivo_Estorno_Venda(null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_estornar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField tb_motivoEstornoVenda;
    // End of variables declaration//GEN-END:variables
}
